import{a as b,S as w,i}from"./assets/vendor-BNibzuFn.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function t(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(o){if(o.ep)return;o.ep=!0;const s=t(o);fetch(o.href,s)}})();const L="https://pixabay.com/api/",v="52479347-3848fb15c35525ad8d42cf6cd";async function d(r,e=1,t=15){return(await b.get(L,{params:{key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:t}})).data}const h=document.querySelector(".gallery"),S=new w(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});function m(r){const e=r.map(t=>`
        <li class='gallery-item'>
    <a class='gallery-link' href='${t.largeImageURL}'>
    <img class='gallery-img' src='${t.webformatURL}' alt='${t.tags}' width='320'/></a>
    <div class='info'>
    <p class='info-item'><b>Likes</b><span class='info-item-current'>${t.likes}</span></p>
    <p class='info-item'><b>Views</b><span class='info-item-current'>${t.views}</span></p>
    <p class='info-item'><b>Comments</b><span class='info-item-current'>${t.comments}</span></p>
    <p class='info-item'><b>Downloads</b><span class='info-item-current'>${t.downloads}</span></p>
    </div></li>`).join("");h.insertAdjacentHTML("beforeend",e),S.refresh()}function q(){h.innerHTML=""}function B(){document.querySelector(".loader").classList.remove("is-unactive")}function f(){document.querySelector(".loader").classList.add("is-unactive")}function p(){document.querySelector(".load-btn").classList.remove("is-unactive")}function g(){document.querySelector(".load-btn").classList.add("is-unactive")}const y=document.querySelector(".form"),M=document.querySelector('[name="search-text"]'),E=document.querySelector(".load-btn");let c="",a=1;const l=15;y.addEventListener("submit",P);async function P(r){if(r.preventDefault(),c=M.value.toLowerCase().trim(),!c){i.error({title:"Error",message:"Enter your search query.",position:"topRight"});return}a=1,q(),g();try{B();const e=await d(c,a,l),t=e.hits;if(!t||t.length===0){i.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(t),e.totalHits>l&&p()}catch(e){console.error(e),i({title:"Error",message:"Something went wrong while loading the images.",position:"topRight"})}finally{f(),y.reset()}E.addEventListener("click",async()=>{a+=1,g();try{const e=await d(c,a,l),t=e.hits;m(t),R();const n=Math.ceil(e.totalHits/l);a<n?p():i.info({title:"End results",message:"Were sorry, but you ve reached the end of search results",position:"topRight"})}catch(e){console.error(e),i({title:"Error",message:"Something went wrong while loading the images.",position:"topRight"})}finally{f()}})}function R(){const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
