import{a as u,S as f,i as a}from"./assets/vendor-D8hBcPQM.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const p="https://pixabay.com/api/",d="52479347-3848fb15c35525ad8d42cf6cd";function m(s){return u.get(p,{params:{key:d,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(o=>o.data)}const c=document.querySelector(".gallery"),y=new f(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});function g(s){const o=s.map(t=>`
        <li class='gallery-item'>
    <a class='gallery-link' href='${t.largeImageURL}'>
    <img class='gallery-img' src='${t.webformatURL}' alt='${t.tags}' width='320'/></a>
    <div class='info'>
    <p class='info-item'><b>Likes</b><span class='info-item-current'>${t.likes}</span></p>
    <p class='info-item'><b>Views</b><span class='info-item-current'>${t.views}</span></p>
    <p class='info-item'><b>Comments</b><span class='info-item-current'>${t.comments}</span></p>
    <p class='info-item'><b>Downloads</b><span class='info-item-current'>${t.downloads}</span></p>
    </div></li>`).join("");c.insertAdjacentHTML("beforeend",o),y.refresh()}function h(){c.innerHTML=""}function b(){document.querySelector(".loader").classList.remove("is-unactive")}function L(){document.querySelector(".loader").classList.add("is-unactive")}const l=document.querySelector(".form"),w=document.querySelector('[name="search-text"]');l.addEventListener("submit",v);function v(s){s.preventDefault();const o=w.value.toLowerCase().trim();if(!o){a.error({title:"Error",message:"Enter your search query.",position:"topRight"});return}l.reset(),h(),b(),m(o).then(t=>{const n=t.hits;if(!n||n.length===0){a.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(n)}).catch(t=>{console.error(t),a({title:"Error",message:"Something went wrong while loading the images.",position:"topRight"})}).finally(()=>{L()})}
//# sourceMappingURL=index.js.map
